# Generated by Django 2.1.4 on 2018-12-24 18:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('cheese', 'Cheese'), ('chicken', 'Chicken'), ('mushroom', 'Mushroom')], default='cheese', max_length=15, verbose_name='Пицца')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='pizza_img')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Pizza'),
        ),
    ]
