# Generated by Django 2.1.4 on 2018-12-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name_slug',
            field=models.CharField(default='', max_length=150),
        ),
    ]
